language: r
sudo: required

# R version
r: bioc-release

# Package caching only makes sense for the release versions.
cache: packages

# Packages from Bioconductor needed
bioc_required: true

# Package dependencies installed using apt-get
apt_packages:
  - gsl-bin
  - libgsl0-dev

# Be strict when checking package
warnings_are_errors: true

# Package dependencies from CRAN
r_binary_packages:
  - RUnit
  - knitr
  - rmarkdown
  - MCMCpack

# Package dependencies from Bioconductor
bioc_packages:
  - BiocGenerics
  - GenomeInfoDb
  - IRanges
  - BiocStyle
  - GenomicRanges
  - PING

# Package dependencies from github
r_github_packages:
  - jimhester/covr
  - arnauddroitlab/consensusseeker
  - arnauddroitlab/nucleoSim

after_success:
  - Rscript -e 'library(covr);codecov()'
