language: r
sudo: required

# R version
r: bioc-release

# Package caching only makes sense for the release versions.
cache: packages

# Packages from Bioconductor needed
bioc_required: true

# Package dependencies installed using apt-get
apt_packages:
  - gsl-bin
  - libgsl0-dev

# Be strict when checking package
warnings_are_errors: true

# Package dependencies from CRAN
r_binary_packages:
  - covr

# Package dependencies from github
r_github_packages:
  - arnauddroitlab/consensusseeker
  - arnauddroitlab/nucleoSim

after_success:
  - Rscript -e 'library(covr);codecov()'
